# Form implementation generated from reading ui file 'ui_template_line_group.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(994, 510)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 380, 30))
        self.groupBox.setObjectName("groupBox")
        self.revise = QtWidgets.QPushButton(parent=self.groupBox)
        self.revise.setGeometry(QtCore.QRect(300, 10, 75, 20))
        self.revise.setObjectName("revise")
        self.plus = QtWidgets.QPushButton(parent=self.groupBox)
        self.plus.setGeometry(QtCore.QRect(240, 10, 20, 20))
        self.plus.setObjectName("plus")
        self.num_of_facs = QtWidgets.QLabel(parent=self.groupBox)
        self.num_of_facs.setGeometry(QtCore.QRect(180, 10, 54, 20))
        self.num_of_facs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.num_of_facs.setObjectName("num_of_facs")
        self.prod_what = QtWidgets.QLabel(parent=self.groupBox)
        self.prod_what.setGeometry(QtCore.QRect(0, 10, 54, 20))
        self.prod_what.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.prod_what.setObjectName("prod_what")
        self.output_num_predict = QtWidgets.QLabel(parent=self.groupBox)
        self.output_num_predict.setGeometry(QtCore.QRect(60, 10, 54, 20))
        self.output_num_predict.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_num_predict.setObjectName("output_num_predict")
        self.minus = QtWidgets.QPushButton(parent=self.groupBox)
        self.minus.setGeometry(QtCore.QRect(270, 10, 20, 20))
        self.minus.setObjectName("minus")
        self.output_num_sum = QtWidgets.QLabel(parent=self.groupBox)
        self.output_num_sum.setGeometry(QtCore.QRect(120, 10, 54, 20))
        self.output_num_sum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_num_sum.setObjectName("output_num_sum")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.revise.setText(_translate("Form", "setup"))
        self.plus.setText(_translate("Form", "+"))
        self.num_of_facs.setText(_translate("Form", "facs"))
        self.prod_what.setText(_translate("Form", "what"))
        self.output_num_predict.setText(_translate("Form", "predict"))
        self.minus.setText(_translate("Form", "-"))
        self.output_num_sum.setText(_translate("Form", "outsum"))
